name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ] # Ana kola kod attığında çalışır

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3

      - name: Docker Hub'a Giriş Yap
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 1. BACKEND İŞLEMLERİ
      - name: Backend Paketle ve Gönder
        uses: docker/build-push-action@v4
        with:
          context: .
          file: WebApi/WebApi/Dockerfile
          push: true
          tags: batuhanxbayram1/koop-api:latest

      # 2. FRONTEND İŞLEMLERİ
      - name: Frontend Paketle ve Gönder
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile # React Dockerfile'ı ana dizinde olduğu için
          push: true
          tags: batuhanxbayram1/koop-react:latest